### ISSUE TITLE
Beta-tester Jasper

### ISSUE THREAD

**Issue by Kbentekik** [gplv2/grb2pgsql#1]
Import test:

-Kastanjeplein, 9790 Wortegem-Petegem
Na vlug doorlezen documentatie op de site, en spelen met de knoppen lijkt alles vrij logisch in gebruik.
Met een druk op de knop zelfs zicht in google streetview :)
Waar de Labels on/off knop voor dient blijft momenteel een raadsel.
De huizen van het kastanjeplein waren vrij snel in JOSM geimporteerd.
Vergelijking met AGIV zorgt bij mij voor twijfel. IS de GRB data verschoven, of kijk ik me mis op de hoek van de getrokken luchtbeelden?

Status: Wachtend op feedback voor verdere test (upload)

**Comment by gplv2** [comment]
De labels on/off  zal je niet zien bewegen tenzij je uitzoomt/inzoomt en/of pan op de kaart.  Het is vooral een dev tool zodat ik in 1 overzicht kon zien wat er op de kaart stond.  wss vliegt dat eraf voor productie want dat was dus vooral dev hulp.  Probeer maar eens op  ON te zetten en dan uit/in te zoomen.

De streetview zal proberen een streetview aan te vragen op google van de locatie van de laatste muisklik.  Dat is idd heel handig voor uitsluitsel te krijgen.   De reden dat je twijfelt ivm de sateliet foto's is omdat je ervan uitgaat dat ze in een hoek van 90 graden getrokken zijn, en dat is meestal niet het geval, dus AGIV zal offset tonen.  Kijk hier even voor visuale uitleg over jouw bedenkingen.  

http://wiki.openstreetmap.org/wiki/Roof_modelling

**Comment by Kbentekik** [comment]
-Kastanjeplein, 9790 Wortegem-Petegem geupload.
Achteraf nog 1 huis aangepast volgens AGIV Image. Volgens mij nieuwbouw.

-Sheds apart geimporteerd en geupload (nochtans niet gefilterd oorspronkelijk).
 Hier enkele wijzigingen moeten maken, soms 3-hoekige gebouwen, terwijl ze zeker vierkant zijn.

-Roof apart geimporteerd. Nagekeken met streetview en bleek juist.

-Gestart om Lindestraat, 9790 Wortegem-Petegem te importeren.
Is een relatief lange straat met rijhuizen. Kan enkel deel per deel importeren aangezien je blijkbaar diep genoeg moet ingezoomd zijn om de GRB-layer te zien. Duurt ook vrij lang tot de straten verschijnen om te filteren. Eens je dan klikt op de straat in de filter, wordt er automatisch ingezoomd of verschoven. Hierdoor moeilijk om het gewenste gebied te importeren.

PS: Dit alles niet bedoeld als kritiek, enkel mijn gebruikservaring. Volgens mij krachtige tool, maar is zaak om hem goed te gebruiken. Verleiding is groot om vlug te importeren.

**Comment by Kbentekik** [comment]
Markt Oudenaarde Import

-Sommige huizen hebben meerdere nummers (voorbeeld verschillende cafés in 1 gebouw)
 Achteraf op te delen?

**Comment by gplv2** [comment]
Oei, blijkbaar zie ik deze reacties niet direct.  Er komt een meetup aan en handleidingen, al die zaken aangehaald kunnen worden uitgelegd/getrained.

**Comment by Kbentekik** [comment]
Geen probleem.
Ik heb niet meer verder gedaan omdat ik momenteel geen tijd meer heb (niet
omdat je niet reageerde).
Neemt niet weg dat ik dit project nog altijd enorm belangrijk vind voor
OSM-vlaanderen.
Bij een finale versie wil ik zeker een deel van mijn regio doen.

Veel succes!

Op 22 november 2016 22:27 schreef Glenn Plas notifications@github.com:
